-- MySQL Script generated by MySQL Workbench
-- Sat Apr  8 09:01:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MS-C-MD_V03
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MS-C-MD_V03
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MS-C-MD_V03` DEFAULT CHARACTER SET utf8 ;
USE `MS-C-MD_V03` ;

-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`atividades` (
  `ID_atividade` INT NOT NULL AUTO_INCREMENT,
  `COD-atividade` VARCHAR(45) NULL,
  `nome_da_atividade` VARCHAR(120) NOT NULL,
  `descrição_da_atividade` LONGTEXT NULL,
  `periodicidade` ENUM('manhã', 'tarde', 'noite', 'madrugada', 'integral', 'diário', 'semanal', 'mensal', 'ocasional') NULL,
  `Duração` ENUM('1h', '2h', '3h', '4h', '5h', '6h', '7h', '8h', '12h', '18h', '24h', '36h') NULL,
  `competencia_exigida` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID_atividade`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`Organização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`Organização` (
  `ID_setor` INT NOT NULL AUTO_INCREMENT,
  `COD_setor` VARCHAR(45) NULL,
  `Nome_do_setor` VARCHAR(120) NOT NULL,
  `Responsável` INT NULL,
  `Descrição_setor` LONGTEXT NULL,
  `Instância_superior` INT NULL,
  PRIMARY KEY (`ID_setor`),
  INDEX `fk_Organização_Organização1_idx` (`Instância_superior` ASC) VISIBLE,
  CONSTRAINT `fk_Organização_Organização1`
    FOREIGN KEY (`Instância_superior`)
    REFERENCES `MS-C-MD_V03`.`Organização` (`ID_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`elementos` (
  `ID_elemento` INT NOT NULL AUTO_INCREMENT,
  `COD_elemento` VARCHAR(45) NULL,
  `nome_do_elemento` VARCHAR(120) NOT NULL,
  `tipo_de_elemento` VARCHAR(45) NULL,
  `Identificador_externo_elemento` VARCHAR(45) NULL,
  `classe` VARCHAR(45) NULL,
  `ocupado_por` INT NULL,
  `Tipo de superfície` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_elemento`),
  INDEX `fk_elementos_setor1_idx` (`ocupado_por` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`funções`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`funções` (
  `ID_função` INT NOT NULL AUTO_INCREMENT,
  `COD_função` VARCHAR(45) NULL,
  `nome_da_função` VARCHAR(120) NOT NULL,
  `descrição_da_função` LONGTEXT NULL,
  `lotação_funcional` INT NULL,
  `subordinação_funcional` INT NULL,
  PRIMARY KEY (`ID_função`),
  INDEX `fk_funções_Organização1_idx` (`lotação_funcional` ASC) VISIBLE,
  INDEX `fk_funções_funções1_idx` (`subordinação_funcional` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`pessoas` (
  `ID_pessoa` INT NOT NULL AUTO_INCREMENT,
  `COD_pessoa` VARCHAR(45) NULL,
  `nome_da_pessoa` VARCHAR(120) NOT NULL,
  `competencias` MEDIUMTEXT NULL,
  `tipo_de_pessoa` ENUM('fisica', 'juridica') NULL,
  `contato` VARCHAR(500) NULL,
  `registro` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_pessoa`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`projetos` (
  `ID_projeto` INT NOT NULL AUTO_INCREMENT,
  `COD_projeto` VARCHAR(45) NULL,
  `nome_do_projeto` VARCHAR(120) NOT NULL,
  `descrição_do_projeto` MEDIUMTEXT NULL,
  `inicio` DATE NULL,
  `fim` DATE NULL,
  `responsável` INT NULL COMMENT 'indica informações do projeto',
  `setor_promotor` INT NULL,
  `equipe` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_projeto`),
  UNIQUE INDEX `nome_do_projeto` (`nome_do_projeto` ASC) VISIBLE,
  INDEX `fk_projetos_funções1_idx` (`responsável` ASC) VISIBLE,
  INDEX `fk_projetos_setor1_idx` (`setor_promotor` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`relações_atividades_elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`relações_atividades_elementos` (
  `ID_atividade_elemento` INT NOT NULL AUTO_INCREMENT,
  `atividade` INT NOT NULL,
  `relação_atividade_elemento` ENUM('utiliza', 'aciona', 'ocupa', 'circula por') NULL,
  `elemento` INT NOT NULL,
  `tipo de acesso ao elemento` ENUM('livre', 'preferencial', 'restrito') NULL,
  PRIMARY KEY (`ID_atividade_elemento`, `atividade`, `elemento`),
  INDEX `fk_r_atividades_elementos_atividades1_idx` (`atividade` ASC) VISIBLE,
  INDEX `fk_r_atividades_elementos_elementos1_idx` (`elemento` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`relações_funções_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`relações_funções_atividades` (
  `ID_função_atividade` INT NOT NULL AUTO_INCREMENT,
  `função_responsável` INT NOT NULL,
  `atividade_encumbida` INT NOT NULL,
  PRIMARY KEY (`ID_função_atividade`, `função_responsável`, `atividade_encumbida`),
  INDEX `fk_r_funções_atividades_funções1_idx` (`função_responsável` ASC) VISIBLE,
  INDEX `fk_r_funções_atividades_atividades1_idx` (`atividade_encumbida` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`relações_pessoas_funções`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`relações_pessoas_funções` (
  `ID_pessoa_função` INT NOT NULL AUTO_INCREMENT,
  `pessoa_encarregada` INT NOT NULL,
  `relação_pessoa_função` ENUM('atribuida a') NULL,
  `função_designada` INT NOT NULL,
  PRIMARY KEY (`ID_pessoa_função`, `função_designada`, `pessoa_encarregada`),
  INDEX `fk_r_pessoas_funções_pessoas_idx` (`pessoa_encarregada` ASC) VISIBLE,
  INDEX `fk_r_pessoas_funções_funções1_idx` (`função_designada` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`relações_elementos_elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`relações_elementos_elementos` (
  `ID_elemento_elemento` INT NOT NULL AUTO_INCREMENT,
  `elemento_referido` INT NOT NULL,
  `relação_elemento_elemento` ENUM('delimita', 'controla acesso', 'pavimenta', 'aciona', 'contem', 'se conecta a') NULL,
  `elemento_referente` INT NOT NULL,
  PRIMARY KEY (`ID_elemento_elemento`, `elemento_referido`, `elemento_referente`),
  INDEX `fk_elementos_has_elementos_elementos2_idx` (`elemento_referente` ASC) VISIBLE,
  INDEX `fk_elementos_has_elementos_elementos1_idx` (`elemento_referido` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`relações_atividades_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`relações_atividades_atividades` (
  `ID_atividade_atividade` INT NOT NULL AUTO_INCREMENT,
  `Atividade_referida` INT NOT NULL,
  `relação_atividade_atividade` ENUM('independende', 'inicia depois do fim de', 'Termina antes do inicio de', 'termina com', 'inicia com', 'ocorre durante', 'é precedida por', 'impede a', 'permite a') NULL,
  `Atividade_referente` INT NOT NULL,
  PRIMARY KEY (`ID_atividade_atividade`, `Atividade_referida`, `Atividade_referente`),
  INDEX `fk_atividades_has_atividades_atividades2_idx` (`Atividade_referente` ASC) VISIBLE,
  INDEX `fk_atividades_has_atividades_atividades1_idx` (`Atividade_referida` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`subsistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`subsistema` (
  `ID_subsistema` INT NOT NULL,
  `COD_subsistema` VARCHAR(45) NULL,
  `nome_do_subsistema` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_subsistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`subprocesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`subprocesso` (
  `ID_subprocesso` INT NOT NULL,
  `COD_subprocesso` VARCHAR(45) NULL,
  `nome_do_subprocesso` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_subprocesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`subprocesso_has_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`subprocesso_has_atividades` (
  `subprocesso_ID_subprocesso` INT NOT NULL,
  `atividades_ID_atividade` INT NOT NULL,
  PRIMARY KEY (`subprocesso_ID_subprocesso`, `atividades_ID_atividade`),
  INDEX `fk_subprocesso_has_atividades_atividades1_idx` (`atividades_ID_atividade` ASC) VISIBLE,
  INDEX `fk_subprocesso_has_atividades_subprocesso1_idx` (`subprocesso_ID_subprocesso` ASC) VISIBLE,
  CONSTRAINT `fk_subprocesso_has_atividades_subprocesso1`
    FOREIGN KEY (`subprocesso_ID_subprocesso`)
    REFERENCES `MS-C-MD_V03`.`subprocesso` (`ID_subprocesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subprocesso_has_atividades_atividades1`
    FOREIGN KEY (`atividades_ID_atividade`)
    REFERENCES `MS-C-MD_V03`.`atividades` (`ID_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS-C-MD_V03`.`elementos_has_subsistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS-C-MD_V03`.`elementos_has_subsistema` (
  `elementos_ID_elemento` INT NOT NULL,
  `subsistema_ID_subsistema` INT NOT NULL,
  PRIMARY KEY (`elementos_ID_elemento`, `subsistema_ID_subsistema`),
  INDEX `fk_elementos_has_subsistema_subsistema1_idx` (`subsistema_ID_subsistema` ASC) VISIBLE,
  INDEX `fk_elementos_has_subsistema_elementos1_idx` (`elementos_ID_elemento` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
